# TODO(waigani) migrate all platform config opts to this file.

all:
  addr: codelingo.io
  grpc_port: "8002"
  gitserver:
    remote:
      name: "codelingo"
      addr: "http://codelingo.io"
      port: "3030"
dev:
  addr: localhost
  gitserver:
    remote:
      name: "codelingo_dev"
      addr: "http://localhost"
      port: "3000"
test:
  addr: localhost
  gitserver:
    remote:
      name: "codelingo_dev"
