all:
  addr: codelingo.io
  gitserver:
    remote:
      addr: http://codelingo.io
      name: new-name
      port: "3030"
  grpc_port: "8002"
dev:
  addr: localhost
  blah:
    gitserver:
      remote:
        name:
          nested:
            super: new-name
            x: b
  gitserver:
    remote:
      addr: http://localhost
      name: codelingo_dev
      port: "3000"
mock:
  blah:
    gitserver:
      remote:
        name:
          nested:
            super: new-name
            x: b
test:
  addr: localhost
  blah:
    gitserver:
      remote:
        name:
          nested:
            super: new-name
            x: b
  gitserver:
    remote:
      name: codelingo_dev
