all:
  addr: codelingo.io
  gitserver:
    remote:
      addr: http://codelingo.io
      name: new-name
      port: "3030"
  grpc_port: "8002"
blah:
  gitserver:
    remote:
      name:
        nested:
          super: new-name
          x: b
dev:
  addr: localhost
  gitserver:
    remote:
      addr: http://localhost
      name: codelingo_dev
      port: "3000"
test:
  addr: localhost
  gitserver:
    remote:
      name: codelingo_dev
