version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/codelingo/lingo
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep

      - run: dep ensure -v
      - run: go test $(go list ./... | grep -v /vendor/)
